# jdr-generator-chart/templates/secrets.yaml
{{- if .Values.secrets.apiKeys.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.apiKeys.existingSecretName }}
  labels:
    {{- include "jdr-generator-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-keys
type: Opaque
stringData:
  # C'est ici que les clés sont injectées dynamiquement lors du déploiement
  {{- range $key, $value := .Values.secrets.apiKeys.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
# Secret pour les identifiants MySQL
{{- if .Values.secrets.mysql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mysql.existingSecretName }}
  labels:
    {{- include "jdr-generator-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql-secrets
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.mysql.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}