apiVersion: v2
name: jdr-generator-gcloud
description: A Kubernetes Helm chart for JDR-Generator API on Google Cloud
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: https://github.com/NeoRyu/JDR-Generator/blob/kubernetes/web/favicon.png