logging:
  level:
    ROOT: INFO
    org.springboot.security: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdr-generator_db?verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Europe/Amsterdam
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: NeoRyu
    password:
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      org.hibernate.flushMode: COMMIT
    show-sql: false
    hibernate:
      ddl-auto: none
      #ddl-auto: update

  servlet:
    multipart:
      max-file-size: 400000000
      max-request-size: 400000000

  messages:
    encoding: UTF-8

server:
  port: 8080
  tomcat:
    max-swallow-size: 500000000
    uri-encoding: UTF-8
    max-http-form-post-size: 500000000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
