logging:
  level:
    ROOT: WARN
    org.springboot.security: ERROR
    jdr.generator.api: DEBUG

# Configuration de l'URL de l'API des IA
GEMINI_API_URL: http://gemini-container:3001/gemini
OPENAI_API_URL: http://openai-container:3002/openai

spring:
  application:
    name: api
  datasource:
    hostname: jdr-generator-db.cbce0mokaknz.eu-west-3.rds.amazonaws.com
    port: 3306
    schema-name: jdr_generator_db
    args: "?verifyServerCertificate=false&autoReconnect=true&useSSL=false&requireSSL=false&serverTimezone=Europe/Amsterdam"
    url: jdbc:mysql://${spring.datasource.hostname}:${spring.datasource.port}/${spring.datasource.schema-name}${spring.datasource.args}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      maxLifetime: 1800000 # 30 minutes
      connectionTimeout: 30000 # 30 secondes
      leakDetectionThreshold: 20000 # 20 secondes
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  flyway:
    enabled: true
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: [ "classpath:db/migration" ]
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${spring.datasource.schema-name}
  jpa:
    #  SHOW VARIABLES LIKE "%version%"; ## check InnoDB version ::
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      org.hibernate.flushMode: COMMIT
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      #ddl-auto: update
  servlet:
    multipart:
      max-file-size: 400000000
      max-request-size: 400000000
  messages:
    encoding: UTF-8

server:
  port: 8080
  tomcat:
    max-swallow-size: 500000000
    uri-encoding: UTF-8
    max-http-form-post-size: 500000000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Indique si l'application s'exécute dans un environnement Docker
is-running-in-docker: ${IS_DOCKER:false}
