# jdr-generator-chart/ai-secrets-values.yaml

# CE FICHIER NE DOIT PAS ÊTRE COMMIS SUR GIT AVEC LES API_KEY SAISIES !
secrets:
  apiKeys:
    data:
      GEMINI_API_KEY: "TODO"
      FREEPIK_API_KEY: "TODO"
      OPENAI_API_KEY: "TODO"
      OPENAI_ORG_ID: "TODO"