# jdr-generator-chart/values.yaml

# Valeurs globales pour le chart
# imagePullSecrets: [] # Décommentez et configurez si vous utilisez un registre privé
# nameOverride: "" # Pour surcharger le nom du chart
# fullnameOverride: "" # Pour surcharger le nom complet (release-name-chart-name)

# Configuration de la section GEMINI
gemini:
  enabled: true
  replicaCount: 1
  image:
    repository: eli256/jdr-generator-gemini
    pullPolicy: IfNotPresent
    tag: "latest"
  containerPort: 3001
  service:
    type: ClusterIP
    port: 3001
  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "300m"
  apiKeyExistingSecret: "jdr-generator-api-secrets"
  apiKeySecretKey: "GEMINI_API_KEY"
  
# Configuration de la section OPENAI
openai:
  enabled: true
  replicaCount: 1
  image:
    repository: eli256/jdr-generator-openai
    pullPolicy: IfNotPresent
    tag: "latest"
  containerPort: 3002
  service:
    type: ClusterIP
    port: 3002
  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "300m"
  apiKeyExistingSecret: "jdr-generator-api-secrets"
  apiKeySecretKey: "OPENAI_API_KEY"
  orgIdExistingSecret: "jdr-generator-api-secrets"
  orgIdSecretKey: "OPENAI_ORG_ID"

# Configuration de la section FREEPIK
freepik:
  enabled: true
  replicaCount: 1
  image:
    repository: eli256/jdr-generator-freepik
    pullPolicy: IfNotPresent
    tag: "latest"
  containerPort: 3003
  service:
    type: ClusterIP
    port: 3003
  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "300m"
  apiKeyExistingSecret: "jdr-generator-api-secrets"
  apiKeySecretKey: "FREEPIK_API_KEY"

# Configuration de la section WEB
web:
  enabled: true
  replicaCount: 1
  image:
    repository: eli256/jdr-generator-web
    pullPolicy: IfNotPresent
    tag: "latest"
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "300m"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  livenessProbe: {}
  readinessProbe: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumes: []
  volumeMounts: []

# Configuration de la section MYSQL
mysql:
  enabled: true
  replicaCount: 1
  image:
    tag: "5.7"
  rootPassword: "root"
  username: "jdr_user"
  password: "root"
  databaseName: "jdr_generator_db"
  existingSecret: "jdr-generator-mysql-secrets"
  persistence:
    size: 5Gi
  service:
    port: 3306

# Configuration de la section API
api:
  enabled: true
  replicaCount: 1
  image:
    repository: eli256/jdr-generator-api
    pullPolicy: IfNotPresent
    tag: "latest"
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080
  extraEnv:
    - name: SPRING_PROFILES_ACTIVE
      value: "kubernetes"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "1"
  readinessProbe:
    httpGet:
      path: /actuator/health
    failureThreshold: 3
    timeoutSeconds: 7
    periodSeconds: 15
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /actuator/health
    failureThreshold: 3
    timeoutSeconds: 7
    periodSeconds: 15
    initialDelaySeconds: 45


# Configuration de la section CONFIGMAPS
configmaps:
  # Configuration des CONFIGMAPS
  api:
    enabled: true
    data:
      SPRING_PROFILES_ACTIVE: "prod,kubernetes"
      MAX_TOKEN: "2048"
      DOWNLOAD_FOLDER: "jdr-generator"
      USER_WINDOW: "fredericcoupez"

  web:
    enabled: true
    data:
      VITE_API_URL: "/"

  gemini:
    enabled: true
    data:
      AI_TEXT_MODEL: "gemini-2.0-flash"
      AI_IMAGE_MODEL: "gemini-2.0-flash-exp-image-generation"

  freepik:
    enabled: true
    data:
      AI_LIST: "https://www.freepik.com/api/pricing"

  openai:
    enabled: true
    data:
      AI_TEXT_MODEL: "gpt-4o-mini"
      AI_IMAGE_MODEL: "dall-e-3"
      AI_LIST: "https://platform.openai.com/docs/models"

secrets:
  mysql:
    enabled: true
  gemini:
    enabled: true
  openai:
    enabled: true
  freepik:
    enabled: true

# serviceAccount:
#   create: true
#   automount: true
#   annotations: {}
#   name: ""
