// listes/gameUniverses.tsx
export const gameUniverses = [
  { value: "undefined", label: "Univers générique" },
  { value: "Aria", label: "Aria" },
  { value: "Ars Magica", label: "Ars Magica" },
  { value: "Brigandyne", label: "Brigandyne" },
  { value: "Chill", label: "Chill" },
  { value: "COPS", label: "COPS" },
  { value: "Cyberpunk RED", label: "Cyberpunk RED" },
  { value: "Call of Cthulhu", label: "L'Appel de Cthulhu" },
  { value: "Das Schwarze Auge", label: "L'Œil noir" },
  { value: "Dune", label: "Dune" },
  { value: "Dungeons & Dragons", label: "Donjons & Dragons" },
  { value: "Legends of the five Rings", label: "La Légende des Cinq Anneaux" },
  { value: "Lone Wolf", label: "Loup Solitaire" },
  { value: "Maléfices", label: "Maléfices" },
  { value: "Midnight", label: "Midnight" },
  { value: "Nightprowler", label: "Nightprowler" },
  { value: "Pathfinder", label: "Pathfinder" },
  { value: "Pendragon", label: "Pendragon" },
  { value: "Rêve de Dragon", label: "Rêve de Dragon" },
  { value: "Shadowrun", label: "Shadowrun" },
  { value: "Shaan", label: "Shaan" },
  { value: "Star Wars", label: "Star Wars" },
  { value: "Vermine", label: "Vermine" },
  { value: "Vampire The Masquerade", label: "Vampire : La Mascarade" },
  { value: "Warhammer Fantasy Roleplay", label: "Warhammer Fantasy Roleplay" },
  { value: "Warhammer 40K", label: "Warhammer 40K" },
  { value: "Würm", label: "Würm" },
];
