// listes/illustrationDrawStyles.tsx
export const illustrationDrawStyles = [
    { value: "photoRealistic", label: "Photo-réaliste" },
    { value: "oldSchool", label: "Old School" },
    { value: "fantasyArt", label: "Fantasy Art" },
    { value: "anime", label: "Anime" },
    { value: "cartoon", label: "Cartoon" },
    { value: "sciFi", label: "Sci-Fi" },
    { value: "steampunk", label: "Steampunk" },
    { value: "gothic", label: "Gothique" },
    { value: "watercolour", label: "Aquarelle" },
    { value: "pixelArt", label: "Pixel Art" },
    { value: "comicBook", label: "Bande Dessinée" },
    { value: "minimalist", label: "Minimaliste" },
    { value: "abstract", label: "Abstrait" },
    { value: "oilPainting", label: "Peinture à l'huile" },
    { value: "pencilSketch", label: "Croquis au crayon" },
    { value: "impressionistic", label: "Impressionniste" },
    { value: "surrealist", label: "Surréaliste" },
    { value: "conceptArt", label: "Concept Art" },
    { value: "childrenBook", label: "Livre pour enfants" },
    { value: "ukiyoE", label: "Ukiyo-e" },
    { value: "artNouveau", label: "Art Nouveau" },
    { value: "dystopian", label: "Dystopien" },
    { value: "cyberPunk", label: "Cyberpunk" },
];