# kubernetes/00-secrets.yaml
# > kubectl apply -f kubernetes/00-secrets.yaml
#   kubectl get secrets

apiVersion: v1
# kubectl apply -f kubernetes/00-secrets.yaml
kind: Secret
metadata:
  name: jdr-generator-mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root" # <-- TODO : À remplacer par un mot de passe root fort
  MYSQL_DATABASE: "jdr_generator_db"
  MYSQL_USER: "jdr_user"
  MYSQL_PASSWORD: "root" # <--  TODO : À remplacer par un mot de passe user fort
---
apiVersion: v1
kind: Secret
metadata:
  name: jdr-generator-ai-secret
type: Opaque # [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes('VOTRE_VRAIE_CLE_API'))
stringData:
  GEMINI_API_KEY: "VOTRE_CLE_API_GEMINI"    # <-- TODO : REMPLACEZ PAR VOTRE VERITABLE CLÉ GEMINI
  FREEPIK_API_KEY: "VOTRE_CLE_API_FREEPIK"  # <-- TODO : REMPLACEZ PAR VOTRE VERITABLE CLÉ FREEPIK
  OPENAI_API_KEY: "VOTRE_CLE_API_OPENAI"    # <-- TODO : REMPLACEZ PAR VOTRE VERITABLE CLÉ OPENAI
  OPENAI_ORG_ID: "VOTRE_ORG_ID"             # <-- TODO : REMPLACEZ PAR VOTRE ID D'ORGANISAT. OPENAI

