version: '3.8'

services:
  mysql-container:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jdr_generator_db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g

  api-container:
    image: eli256/jdr-generator-api:latest
    ports:
      - "8080:8080"
    environment:
      GEMINI_API_URL: http://gemini-container:3001/gemini
      OPENAI_API_URL: http://openai-container:3002/openai
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/jdr_generator_db?verifyServerCertificate=false&autoReconnect=true&useSSL=false&requireSSL=false&serverTimezone=Europe/Amsterdam&connectTimeout=5000&socketTimeout=5000
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none # Flyway gère le schéma
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 1800000
    depends_on:
      mysql-container:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2g

  web-container:
    image: eli256/jdr-generator-web:latest
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://api-container:8080
    depends_on:
      api-container:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g

  gemini-container:
    image: eli256/jdr-generator-gemini:latest
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/gemini/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g

  openai-container:
    image: eli256/jdr-generator-openai:latest
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/openai/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g

volumes:
  mysql-data:
    driver: local
