name: Build and push Docker images

on:
  push:
    branches:
      - githubactions
      - main
    paths:
      - 'api/**'
      - 'web/**'
      - 'gemini/**'
      - 'openai/**'
  workflow_dispatch:
    inputs:
      force_rebuild:
        type: boolean
        description: 'Force la reconstruction de toutes les images (même sans changements)'
        required: false
        default: false

jobs:
  login-dockerhub:
    name: Login to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      logged_in: ${{ steps.login.outcome == 'success' }}
    steps:
      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-web:
    name: Build and push web image
    needs: login-dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: ./web/Dockerfile
          push: ${{ needs.login-dockerhub.outputs.logged_in }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-web:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-web:latest

  build-and-push-api:
    name: Build and push api image
    needs: login-dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          file: ./api/Dockerfile
          push: ${{ needs.login-dockerhub.outputs.logged_in }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-api:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-api:latest

  build-and-push-gemini:
    name: Build and push gemini image
    needs: login-dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./gemini
          file: ./gemini/Dockerfile
          push: ${{ needs.login-dockerhub.outputs.logged_in }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-gemini:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-gemini:latest

  build-and-push-openai:
    name: Build and push openai image
    needs: login-dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./openai
          file: ./openai/Dockerfile
          push: ${{ needs.login-dockerhub.outputs.logged_in }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-openai:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-openai:latest