name: Build and push Docker images

on:
  push:
    branches:
      - githubactions
      - main
    paths:
      - 'api/**'
      - 'web/**'
      - 'gemini/**'
      - 'openai/**'
  workflow_dispatch:
    inputs:
      force_rebuild:
        type: boolean
        description: 'Force la reconstruction de toutes les images (même sans changements)'
        required: false
        default: false

jobs:
  login-dockerhub:
    name: Login to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      logged_in: ${{ steps.login.outcome == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  common_steps:
    name: Common Steps
    runs-on: ubuntu-latest
    outputs:
      checkout_path: ${{ steps.checkout.outputs.path }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  build-and-push-api:
    name: Build and push API docker image
    needs: [login-dockerhub, common_steps]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Use Common Steps Output
        uses: actions/github-script@v7
        with:
          script: console.log('Checked out code at:', context.needs.common_steps.outputs.checkout_path);
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          file: ./api/Dockerfile
          push: ${{ needs.login-dockerhub.outputs.logged_in }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-api:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-api:latest

  build-and-push-gemini:
    name: Build and push GEMINI docker image
    needs: [login-dockerhub, common_steps]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Build and push Docker docker image
        uses: docker/build-push-action@v3
        with:
          context: ./gemini
          file: ./gemini/Dockerfile
          push: ${{ needs.login-dockerhub.outputs.logged_in }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-gemini:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-gemini:latest

  build-and-push-openai:
    name: Build and push OPENAI docker image
    needs: [login-dockerhub, common_steps]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./openai
          file: ./openai/Dockerfile
          push: ${{ needs.login-dockerhub.outputs.logged_in }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-openai:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-openai:latest

  build-and-push-web:
    name: Build and push WEB docker image
    needs: [login-dockerhub, common_steps]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: ./web/Dockerfile
          push: ${{ needs.login-dockerhub.outputs.logged_in }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-web:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/jdr-generator-web:latest
